apiVersion: v1
kind: Namespace
metadata:
  name: language-routing-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
  namespace: language-routing-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      key: first
  template:
    metadata:
      labels:
        key: first
    spec:
      containers:
      - name: hello1
        image: echaffraix/route-displayer:latest
        ports:
        - containerPort: 8080
        env:
          - name: NAME
            value: First
---
apiVersion: v1
kind: Service
metadata:
  name: first
  namespace: language-routing-ns
spec:
  selector:
    key: first
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second
  namespace: language-routing-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      key: second
  template:
    metadata:
      labels:
        key: second
    spec:
      containers:
      - name: hello1
        image: echaffraix/route-displayer:latest
        ports:
        - containerPort: 8080
        env:
          - name: NAME
            value: Second
---
apiVersion: v1
kind: Service
metadata:
  name: second
  namespace: language-routing-ns
spec:
  selector:
    key: second
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-language-routing-rewrite
  namespace: language-routing-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: <% host.example.com %>
    http:
      paths:
      - path: /[f][r](/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: first
            port:
              number: 80
      - path: /[e][n](/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: second
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-language-routing-default
  namespace: language-routing-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: <% host.example.com %>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: first
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-language-routing-fallback
  namespace: language-routing-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: <% host.example.com %>
    http:
      paths:
      - path: /[a-z]{2}/(.*)
        pathType: Prefix
        backend:
          service:
            name: first
            port:
              number: 80